import './globals.css'
import 'bootstrap/dist/css/bootstrap.css';
import "@fortawesome/fontawesome-free/css/all.min.css";
import { Rubik } from 'next/font/google'
import Script from 'next/script'
//components 
import Navbar from './components/Navbar'
import Header from './components/Header'
import MainSection from './components/MainSection'
import CommentsForm from './components/CommentsForm'
import Footer from './components/Footer'
const rubik = Rubik({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar /> 
        <Header /> 
        <MainSection /> 
        <CommentsForm />
        {children}
        <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></Script>
        </body>
    </html>
  )
}
